Rename Database to UserDatabase
UMM-CSci-3601/3601-lab2_client-server pull request #164
Opened 2021-02-09 20:30 UTC by NicMcPhee

In going over the lab in class today, I stumbled across an issue that, while minor, has come up repeatedly over the years. We (& I think it's "I", TBH) called the "fake database" class `Database`. This creates an awkward moment when the students need to make their own to-do database class.

I think that renaming `Database` to `UserDatabase` would help with that in the future. I ended up showing them how to do that in VS Code (so nice), so I figured I'd turn that into a PR. If people are OK with it, it will hopefully make things at least a _little_ better in the future.

2021-02-09 20:33 UTC, NicMcPhee commented on server/src/test/java/umm3601/user/UserControllerSpec.java
> +
I moved this blank line around so that the structure of the method is now:

- Everything _before_ the tested call
- The tested call
- Everything _after_ the tested call

It's not strictly relevant to this PR, so I could pull this out if folks want.

2021-02-09 20:41 UTC, kklamberty submitted a review, later dismissed
I think it's fine to change the name of this fake database to be UserDatabase. Can you help me understand the challenge the old name was posing? Was it harder to "find and replace" things since that's pretty generic for the name? Does this actually save them from needing to create a TodosDatabase? I'm not completely sure I understand. I do not, however, object to this change.

2021-02-09 20:42 UTC, kklamberty commented on server/src/test/java/umm3601/user/UserControllerSpec.java
> +
I think this change should stay as you've done it. No need to pull it out even though it's not strictly about renaming. By itself, it's kinda just too small to make its own branch, etc.

2021-02-09 23:20 UTC, NicMcPhee commented
@kklamberty A "natural" way to do the lab is, as you indicated, to create a `TodoDatabase`. But then the naming is weird because you have `Database` for users, and `TodoDatabase` for to-dos. Some students then start to second guess their understanding.

My thought is that if we just called it `UserDatabase` from the beginning, it would be easier for the students to "pattern match" and create a new `TodoDatabase.java` file/class/etc.

The other option would be to have one `Database` class that handles _both_ users and to-dos, but that gets long, and there are some internal naming problems (there's a `size()` method that would probably have to be renamed `numUsers()`), and it's not clear that we'd have a class serving _one purpose_ anymore.

Does that make sense?

2021-02-10 04:48 UTC, helloworld12321 requested changes
There are a few places in comments we may also want to change. Other than that, looks great! :)

Thanks for doing that, Prof. Nic!

```ag
server/src/test/java/umm3601/user/FilterUsersByCombinedFiltersFromDB.java
14: * Tests umm3601.user.Database listUsers with _age_ and _company_ query

server/src/test/java/umm3601/user/GetUserByIDFromDB.java
10: * Tests umm3601.user.Database getUser functionality

server/src/test/java/umm3601/user/FullUserListFromDB.java
11: * Tests umm3601.user.Database listUser functionality

server/src/test/java/umm3601/user/FilterUsersByAgeFromDB.java
14: * Tests umm3601.user.Database filterUsersByAge and listUsers with _age_ query

server/src/main/java/umm3601/user/UserController.java
20:   * @param database the `Database` containing user data
```

2021-02-13 05:06 UTC, floogulinc commented
This is actually already how it's structured in lab 3.

2021-02-15 16:13 UTC, NicMcPhee commented
Thanks to @helloworld12321 for catching the need to update the references in comments and this fixes that.

Another nice example of the challenges comments bring with them.

2021-02-15 16:57 UTC, helloworld12321 approved these changes
Looks wonderful—thanks, Prof. Nic!

2021-12-15 01:42 UTC, merged