Add Thunder client to recommended extensions
UMM-CSci-3601/3601-lab2_client-server pull request #288
Opened 2023-01-23 05:56 UTC by jpwalbran

Closes #252

2023-01-23 22:18 UTC, kklamberty requested changes
This looks like a great start! I've suggested minor changes to be consistent with the spelling and capitalization as well as a wording change in the heading to be more like the other parts of the writeup.

2023-01-23 22:18 UTC, kklamberty commented on LABTASKS.md
> +Thunder client is a tool for debugging the server API output from VSCode.
```suggestion
Thunder Client is a tool for debugging the server API output from VSCode. 
```

2023-01-23 22:18 UTC, kklamberty commented on LABTASKS.md
> +To use Thunderclient (once it's installed), open it from the sidebar.
```suggestion
To use Thunder Client (once it's installed), open it from the sidebar. 
```

2023-01-23 22:18 UTC, kklamberty commented on LABTASKS.md
> +### Using Thunder Client
```suggestion
### Use Thunder Client to explore API output
```

2023-01-23 22:31 UTC, NicMcPhee reviewed
Thanks to @jpwalbran for starting this!

I would consider extending the text a little to say something about how, for example, to add query parameters. They're mentioned, but nothing is actually shown, and it might be helpful to have an example or two.

Later (perhaps a new PR in Lab 4?), we probably want to extend this further by showing how to do things like PUT and POST requests. That's arguably where Thunder Client truly becomes useful, since we can do all the GET work by just hacking URLs in the browser.

Oh, and we might want to also point out that you can save queries and give them names, so you can re-run them later.

2023-01-23 22:31 UTC, NicMcPhee commented on LABTASKS.md
> +#### Usage
I don't think it makes sense to have this `Usage` sub-header, especially when when it's in a section that is about _using_ Thunder Client that has almost no other content.

```suggestion
```

2023-01-23 22:31 UTC, NicMcPhee commented on LABTASKS.md
> +Thunder client is a tool for debugging the server API output from VSCode.
I agree that we want to be more consistent in the way we write this (something I'm never good at, TBH).

2023-01-23 22:31 UTC, NicMcPhee commented on LABTASKS.md
> +This should add a button in the top of the sidebar labelled `New Request`, click it.
I'm not sure why, but this line seems to quasi-end a paragraph, but not quite? The next line starts on a new line (instead of extending this one), but doesn't seem to start a new paragraph? Did you embed a carriage return or something like that by accident?

2023-01-23 22:31 UTC, NicMcPhee commented on LABTASKS.md
> +This should add a button in the top of the sidebar labelled `New Request`, click it.
This would also be a good place to add screenshots. @helloworld12321 and @floogulinc have been working to add more screenshots to the write-ups, and I do think they help quite a lot. There's a risk of them aging badly, but that hasn't seemed to have been a huge issue, and I think they convey a lot of useful info to the students.

2023-01-23 22:59 UTC, NicMcPhee requested changes

2023-01-23 22:59 UTC, NicMcPhee commented on LABTASKS.md
> +    - [Usage](#usage)
Make sure to update the ToC (i.e., remove the "Usage" entry).

If you're using the Markdown All In One VSCode extension, it should manage that automatically, but if you make changes here in GitHub then you've got to manage that stuff as well.

2023-01-24 01:08 UTC, kklamberty submitted a review, later dismissed

2023-01-24 02:24 UTC, NicMcPhee approved these changes
Nice!

2023-01-24 02:25 UTC, merged